import { desertColors, desertSpecial } from "./desertColors";

export const desertCodeColors = {
  languages: {
    comment: desertColors.grey,
    general: desertColors.darkerPink,
    brackets: desertColors.white,
    importVar: desertColors.white,
    string: desertColors.green,
    storage: desertColors.red,
    variables: desertColors.white,
    phpVariables: desertSpecial.php,
    constant: desertColors.orange,
    function: desertColors.yellow,
    params: desertColors.gold,
    class: desertColors.blue,
    attributes: desertColors.purple,
    objectMethod: desertColors.limon,
    this: desertColors.purple,
    interface: desertColors.cyan,
    regex: desertColors.purple,
    regexString: desertColors.turquoise,
    regexPositive: desertColors.green,
    regexCharacter: desertColors.pink,
    regexAssertion: desertColors.red,
    jsDocKeyWord: desertColors.pink,
    jsDockTypes: desertColors.cyan,
    jsDockComment: desertColors.gold,
    test: desertColors.red,
    other: desertColors.pink,
  },
  react: {
    classComponent: desertColors.blue,
  },
  vue: {
    default: desertSpecial.vue,
    types: desertColors.cyan,
    variables: desertColors.blue,
    other: desertColors.darkerPink,
    test: desertColors.red,
  },
  json: {
    comment: desertColors.grey,
    brackets: desertColors.white,
    constant: desertColors.orange,
    test: desertColors.red,
  },
  xml: {
    meta: desertColors.darkerPink,
    version: desertColors.darkerPink,
    tag: desertColors.orange,
    attribute: desertColors.purple,
    test: desertColors.red,
  },
  html: {
    meta: desertColors.darkerPink,
    tag: desertColors.orange,
    vueTag: desertColors.green,
    attribute: desertColors.purple,
    text: desertColors.white,
    constant: desertColors.yellow,
    string: desertColors.green,
    test: desertColors.red,
  },
  scss: {
    keyword: desertColors.pink,
    type: desertColors.turquoise,
    meta: desertColors.blue,
    metaScss: desertColors.darkerPink,
    tag: desertColors.orange,
    custom: desertColors.turquoise,
    class: desertColors.blue,
    id: desertColors.red,
    pseudo: desertColors.cyan,
    property: desertColors.purple,
    propertyValue: desertColors.gold,
    unit: desertColors.limon,
    variable: desertColors.darkerPink,
    variable2: desertColors.blue,
    comment: desertColors.grey,
    string: desertColors.green,
    bracket: desertColors.white,
    function: desertColors.yellow,
    test: desertColors.red,
  },
  gitGnoreAtr: {
    string: desertColors.orange,
    hash: desertColors.red,
    test: desertColors.red,
  },
  markdown: {
    header: desertColors.purple,
    source: desertColors.white,
    diff: desertColors.pink,
    inserted: desertColors.green,
    deleted: desertColors.red,
    changed: desertColors.gold,
    invalid: desertColors.red,
    deprecated: desertColors.grey,
    filename: desertColors.yellow,
    error: desertColors.red,
    bold: desertColors.orange,
    italic: desertColors.yellow,
    list: desertColors.cyan,
    inline: desertColors.turquoise,
    links: desertColors.blue,
    linkText: desertColors.pink,
    bloquotes: desertColors.limon,
    horizontal: desertColors.pink,
    codeBlocks: desertColors.green,
    constants: desertColors.orange,
    braces: desertColors.purple,
    bracesParagraph: desertColors.gold,
    bracesBlock: desertColors.turquoise,
    test: desertColors.red,
    other: desertColors.pink,
  },
};
