export const aquaColors = {
  background: "#2b2e4a",
  foreground: "#f6efeb",
  chartreuse: "#94fc13",
  electricLime: "#d2e603",
  aeroBlue: "#c2fcd9",
  turquoise: "#1bf5af",
  aquaMarine: "#74f9ff",
  lilyWhite: "#E3F8FF",
  yellow: "#fff76a",
  sunglow: "#ffc93c",
  lightRed: "#fa7f7f",
  geraldine: "#e84a5f",
  orange: "#ff8b00",
  mauve: "#f5b5fc",
  tickleMePink: "#ff75a0",
  dullLavender: "#A49AE7",
  cornflowerBlue: "#7C6FFF",
  perfume: "#BD93F9",
  fuchsiaBlue: "#845EC2",
  oysterPink: "#EAD3CB",
  dawnPink: "#f6efeb",
  black: "#000",
};

// colors names by: https://imagecolorpicker.com/color-code/94fc13
