import VsCodeTheme from "../utils/classes/VsCodeTheme";
import {
  languages,
  react,
  vue,
  json,
  xml,
  html,
  scss,
  gitGnoreAtr,
  markdown,
} from "../styles/darkAqua";

export const darkAqua = new VsCodeTheme();

darkAqua.name = "Milianor Theme";
darkAqua.type = "dark";
darkAqua.semanticHighlighting = true;
darkAqua.colors = {
  foreground: "#cccccc",
  focusBorder: "#7c6fff",
  "selection.background": "#1c774c",
  "scrollbar.shadow": "#5a7fd5",
  "activityBar.foreground": "#ff75a0",
  "activityBar.background": "#2d334a",
  "activityBar.inactiveForeground": "#f6efeb",
  "activityBarBadge.foreground": "#ffffff",
  "activityBarBadge.background": "#ff75a0",
  "sideBar.background": "#2d334a",
  "sideBar.foreground": "#cccccc",
  "sideBarSectionHeader.background": "#00000000",
  "sideBarSectionHeader.foreground": "#cccccc",
  "sideBarSectionHeader.border": "#cccccc33",
  "sideBarTitle.foreground": "#bbbbbb",
  "list.inactiveSelectionBackground": "#202026",
  "list.inactiveSelectionForeground": "#cccccc",
  "list.hoverBackground": "#2a2d2e",
  "list.hoverForeground": "#cccccc",
  "list.activeSelectionBackground": "#094771",
  "list.activeSelectionForeground": "#ffffff",
  "tree.indentGuidesStroke": "#585858",
  "list.dropBackground": "#2b353d",
  "list.highlightForeground": "#0097fb",
  "list.focusBackground": "#062f4a",
  "list.focusForeground": "#cccccc",
  "listFilterWidget.background": "#653723",
  "listFilterWidget.outline": "#00000000",
  "listFilterWidget.noMatchesOutline": "#be1100",
  "statusBar.foreground": "#ffffff",
  "statusBar.background": "#007acc",
  "statusBarItem.hoverBackground": "#ffffff1f",
  "statusBar.debuggingBackground": "#cc6633",
  "statusBar.debuggingForeground": "#ffffff",
  "statusBar.noFolderBackground": "#68217a",
  "statusBar.noFolderForeground": "#ffffff",
  "statusBarItem.remoteBackground": "#16825d",
  "statusBarItem.remoteForeground": "#ffffff",
  "titleBar.activeBackground": "#2d334a",
  "titleBar.activeForeground": "#cccccc",
  "titleBar.inactiveBackground": "#3c3c3c99",
  "titleBar.inactiveForeground": "#cccccc99",
  "titleBar.border": "#00000000",
  "menubar.selectionForeground": "#cccccc",
  "menubar.selectionBackground": "#ffffff1a",
  "menu.foreground": "#cccccc",
  "menu.background": "#2d334a",
  "menu.selectionForeground": "#ffffff",
  "menu.selectionBackground": "#094771",
  "menu.selectionBorder": "#00000000",
  "menu.separatorBackground": "#bbbbbb",
  "menu.border": "#00000085",
  "button.background": "#ff75a0",
  "button.foreground": "#ffffff",
  "button.hoverBackground": "#ff75a0",
  "button.secondaryForeground": "#ffffff",
  "button.secondaryBackground": "#3a3d41",
  "button.secondaryHoverBackground": "#45494e",
  "input.background": "#3c3c3c",
  "input.border": "#00000000",
  "input.foreground": "#cccccc",
  "inputOption.activeBackground": "#007fd466",
  "inputOption.activeBorder": "#007acc00",
  "inputOption.activeForeground": "#ffffff",
  "input.placeholderForeground": "#a6a6a6",
  "textLink.foreground": "#ff75a0",
  "editor.background": "#2d334a",
  "editor.foreground": "#d4d4d4",
  "editorLineNumber.foreground": "#f6efeb",
  "editorCursor.foreground": "#74f9ff",
  "editorCursor.background": "#000000",
  "editor.selectionBackground": "#265978",
  "editor.inactiveSelectionBackground": "#3a3d41",
  "editorWhitespace.foreground": "#dbdbdb80",
  "editor.selectionHighlightBackground": "#add6ff26",
  "editor.selectionHighlightBorder": "#0174f0",
  "editor.findMatchBackground": "#515c6a",
  "editor.findMatchBorder": "#69a16f",
  "editor.findMatchHighlightBackground": "#d7d41e55",
  "editor.findMatchHighlightBorder": "#fbfbfb00",
  "editor.findRangeHighlightBackground": "#52627766",
  "editor.findRangeHighlightBorder": "#fdfafa00",
  "editor.rangeHighlightBackground": "#fff9f90b",
  "editor.rangeHighlightBorder": "#ffffff00",
  "editor.hoverHighlightBackground": "#0e75db40",
  "editor.wordHighlightStrongBackground": "#0274b4b8",
  "editor.wordHighlightStrongBorder": "#c700e4",
  "editor.wordHighlightBackground": "#575757b8",
  "editor.lineHighlightBackground": "#ffffff0A",
  "editor.lineHighlightBorder": "#282828",
  "editorLineNumber.activeForeground": "#1bf5af",
  "editorLink.activeForeground": "#4e94ce",
  "editorIndentGuide.background": "#404040",
  "editorIndentGuide.activeBackground": "#707070",
  "editorRuler.foreground": "#5a5a5a",
  "editorBracketMatch.background": "#0064001a",
  "editorBracketMatch.border": "#888888",
  "editor.foldBackground": "#264f784d",
  "editorOverviewRuler.background": "#25252500",
  "editorOverviewRuler.border": "#7f7f7f4d",
  "editorError.foreground": "#f48771",
  "editorError.background": "#B73A3400",
  "editorError.border": "#ffffff00",
  "editorWarning.foreground": "#cca700",
  "editorWarning.background": "#A9904000",
  "editorWarning.border": "#ffffff00",
  "editorInfo.foreground": "#75beff",
  "editorInfo.background": "#4490BF00",
  "editorInfo.border": "#4490BF00",
  "editorGutter.background": "#2d334a",
  "editorGutter.modifiedBackground": "#0c7d9d",
  "editorGutter.addedBackground": "#587c0c",
  "editorGutter.deletedBackground": "#94151b",
  "editorGutter.foldingControlForeground": "#f6efeb",
  "editorCodeLens.foreground": "#999999",
  "editorGroup.border": "#f5b5fc",
  "diffEditor.insertedTextBackground": "#9bb95533",
  "diffEditor.removedTextBackground": "#ff000033",
  "diffEditor.border": "#444444",
  "panel.background": "#1e1e1e",
  "panel.border": "#80808059",
  "panelTitle.activeBorder": "#e7e7e7",
  "panelTitle.activeForeground": "#e7e7e7",
  "panelTitle.inactiveForeground": "#e7e7e799",
  "badge.background": "#4d4d4d",
  "badge.foreground": "#ffffff",
  "terminal.foreground": "#cccccc",
  "terminal.selectionBackground": "#ffffff40",
  "terminalCursor.background": "#0087FF",
  "terminalCursor.foreground": "#ffffff",
  "terminal.border": "#80808059",
  "terminal.ansiBlack": "#000000",
  "terminal.ansiBlue": "#2472c8",
  "terminal.ansiBrightBlack": "#666666",
  "terminal.ansiBrightBlue": "#3b8eea",
  "terminal.ansiBrightCyan": "#29b8db",
  "terminal.ansiBrightGreen": "#23d18b",
  "terminal.ansiBrightMagenta": "#d670d6",
  "terminal.ansiBrightRed": "#f14c4c",
  "terminal.ansiBrightWhite": "#e5e5e5",
  "terminal.ansiBrightYellow": "#f5f543",
  "terminal.ansiCyan": "#11a8cd",
  "terminal.ansiGreen": "#0dbc79",
  "terminal.ansiMagenta": "#bc3fbc",
  "terminal.ansiRed": "#cd3131",
  "terminal.ansiWhite": "#e5e5e5",
  "terminal.ansiYellow": "#e5e510",
  "breadcrumb.background": "#2d334a",
  "breadcrumb.foreground": "#cccccccc",
  "breadcrumb.focusForeground": "#e0e0e0",
  "editorGroupHeader.tabsBackground": "#2d334a",
  "tab.activeForeground": "#ffffff",
  "tab.border": "#2d334a",
  "tab.activeBackground": "#2d334a",
  "tab.activeBorder": "#00000000",
  "tab.activeBorderTop": "#00000000",
  "tab.inactiveBackground": "#322f2f",
  "tab.inactiveForeground": "#ffffff80",
  "scrollbarSlider.background": "#79797966",
  "scrollbarSlider.hoverBackground": "#646464b3",
  "scrollbarSlider.activeBackground": "#bfbfbf66",
  "progressBar.background": "#7c6fff",
  "widget.shadow": "#0000005c",
  "editorWidget.foreground": "#cccccc",
  "editorWidget.background": "#2d334a",
  "editorWidget.resizeBorder": "#5F5F5F",
  "pickerGroup.border": "#3f3f46",
  "pickerGroup.foreground": "#3794ff",
  "debugToolBar.background": "#2d334a",
  "debugToolBar.border": "#474747",
  "notifications.foreground": "#cccccc",
  "notifications.background": "#2d334a",
  "notificationToast.border": "#474747",
  "notificationsErrorIcon.foreground": "#f48771",
  "notificationsWarningIcon.foreground": "#cca700",
  "notificationsInfoIcon.foreground": "#75beff",
  "notificationCenter.border": "#474747",
  "notificationCenterHeader.foreground": "#cccccc",
  "notificationCenterHeader.background": "#7c6fff",
  "notifications.border": "#303031",
  "gitDecoration.addedResourceForeground": "#81b88b",
  "gitDecoration.conflictingResourceForeground": "#6c6cc4",
  "gitDecoration.deletedResourceForeground": "#c74e39",
  "gitDecoration.ignoredResourceForeground": "#8c8c8c",
  "gitDecoration.modifiedResourceForeground": "#e2c08d",
  "gitDecoration.stageDeletedResourceForeground": "#c74e39",
  "gitDecoration.stageModifiedResourceForeground": "#e2c08d",
  "gitDecoration.submoduleResourceForeground": "#8db9e2",
  "gitDecoration.untrackedResourceForeground": "#73c991",
  "editorMarkerNavigation.background": "#2d2d30",
  "editorMarkerNavigationError.background": "#fff76a",
  "editorMarkerNavigationWarning.background": "#1bf5af",
  "editorMarkerNavigationInfo.background": "#74f9ff",
  "merge.currentHeaderBackground": "#367366",
  "merge.currentContentBackground": "#27403B",
  "merge.incomingHeaderBackground": "#395F8F",
  "merge.incomingContentBackground": "#28384B",
  "merge.commonHeaderBackground": "#383838",
  "merge.commonContentBackground": "#282828",
  "editorSuggestWidget.background": "#252526",
  "editorSuggestWidget.border": "#454545",
  "editorSuggestWidget.foreground": "#d4d4d4",
  "editorSuggestWidget.highlightForeground": "#0097fb",
  "editorSuggestWidget.selectedBackground": "#062f4a",
  "editorHoverWidget.foreground": "#cccccc",
  "editorHoverWidget.background": "#252526",
  "editorHoverWidget.border": "#454545",
  "peekView.border": "#007acc",
  "peekViewEditor.background": "#001f33",
  "peekViewEditorGutter.background": "#001f33",
  "peekViewEditor.matchHighlightBackground": "#ff8f0099",
  "peekViewEditor.matchHighlightBorder": "#ee931e",
  "peekViewResult.background": "#252526",
  "peekViewResult.fileForeground": "#ffffff",
  "peekViewResult.lineForeground": "#bbbbbb",
  "peekViewResult.matchHighlightBackground": "#ea5c004d",
  "peekViewResult.selectionBackground": "#3399ff33",
  "peekViewResult.selectionForeground": "#ffffff",
  "peekViewTitle.background": "#1e1e1e",
  "peekViewTitleDescription.foreground": "#ccccccb3",
  "peekViewTitleLabel.foreground": "#ffffff",
  "icon.foreground": "#cccccc",
  "checkbox.background": "#3c3c3c",
  "checkbox.foreground": "#cccccc",
  "checkbox.border": "#00000000",
  "dropdown.background": "#3c3c3c",
  "dropdown.foreground": "#cccccc",
  "dropdown.border": "#00000000",
  "minimapGutter.addedBackground": "#587c0c",
  "minimapGutter.modifiedBackground": "#0c7d9d",
  "minimapGutter.deletedBackground": "#94151b",
  "minimap.findMatchHighlight": "#515c6a",
  "minimap.selectionHighlight": "#265978",
  "minimap.errorHighlight": "#f48771",
  "minimap.warningHighlight": "#cca700",
  "minimap.background": "#2d334a",
  "sideBar.dropBackground": "#2b353d",
  "editorGroup.emptyBackground": "#2d334a",
  "panelSection.border": "#80808059",
  "statusBarItem.activeBackground": "#FFFFFF25",
  "settings.headerForeground": "#cccccc",
  "settings.focusedRowBackground": "#ffffff07",
  "walkThrough.embeddedEditorBackground": "#00000050",
  "breadcrumb.activeSelectionForeground": "#e0e0e0",
  "editorGutter.commentRangeForeground": "#f6efeb",
  "debugExceptionWidget.background": "#2d334a",
  "debugExceptionWidget.border": "#474747",
};

darkAqua.tokenColors = [
  ...languages,
  ...react,
  ...vue,
  ...json,
  ...xml,
  ...html,
  ...scss,
  ...gitGnoreAtr,
  ...markdown,
];
