import { CodeColors } from "../../utils/types";
import { goldColors as colors } from "./goldColors";

export const goldCodeColors: CodeColors = {
  languages: {
    comment: colors.stoneGray,
    string: colors.emerald,
    constant: colors.tanzanite,
    variables: colors.marble,
    phpVariables: colors.tanzanite,
    keyword: colors.ruby,
    general: colors.ruby,
    modifier: colors.ruby,
    storage: colors.ruby,
    function: colors.gold,
    objectMethod: colors.diamond,
    class: colors.turquoise,
    types: colors.turquoise,
    this: colors.tanzanite,
    decorator: colors.tanzanite,
    magicFunctions: colors.tanzanite,
    attributes: colors.diamond,
    generics: colors.oldGold,
    buildIn: colors.turquoise,
    params: colors.oldGold,
    brackets: colors.foreground,
    regexString: colors.emerald,
    regexNonCapture: colors.ruby,
    regexConstants: colors.tanzanite,
    regexStartEnd: colors.gemstone,
    charGroup: colors.turquoise,
    captureGroup: colors.oldGold,
    assertionOperator: colors.gemstone,
    positiveLookahead: colors.gold,
    propertyQuotes: colors.turquoise,
    docstring: colors.tanzanite,
    destructuringLhs: colors.oldGold,
    destructuringRhs: colors.marble,
    graphQlKeys: colors.emerald,
    graphQlFuncArgs: colors.oldGold,
    graphQlFragments: colors.turquoise,
    foreground: colors.foreground,
    shellConstant: colors.tanzanite,
    shellVariables: colors.marble,
    makeFile: colors.emerald,
    Haskell: colors.tanzanite,
    aliases: colors.gold,
    keys: colors.turquoise,
    dates: colors.oldGold,
    jsDocKeyWord: colors.ruby,
    jsDockTypes: colors.turquoise,
    jsDockComment: colors.stoneGray,
    diff: colors.tanzanite,
    header: colors.oldGold,
    source: colors.foreground,
  },
  react: {
    classComponent: colors.turquoise,
    source: colors.foreground,
  },
  vue: {
    default: colors.emerald,
    attribute: colors.diamond,
    types: colors.turquoise,
  },
  json: {
    brackets: colors.foreground,
    comment: colors.stoneGray,
    constant: colors.tanzanite,
  },
  xml: {
    meta: colors.foreground,
    version: colors.foreground,
    attribute: colors.diamond,
    tag: colors.gemstone,
  },
  html: {
    meta: colors.ruby,
    attribute: colors.diamond,
    string: colors.emerald,
    constant: colors.ruby,
    tag: colors.ruby,
    text: colors.foreground,
    comment: colors.stoneGray,
  },
  scss: {
    meta: colors.gemstone,
    generics: colors.gemstone,
    keyword: colors.gemstone,
    metaScss: colors.gemstone,
    parentSelector: colors.gemstone,
    comment: colors.stoneGray,
    bracket: colors.foreground,
    cssVar: colors.marble,
    scssVar: colors.ruby,
    class: colors.turquoise,
    function: colors.gold,
    string: colors.emerald,
    property: colors.diamond,
    propertyValue: colors.bronze,
    custom: colors.tanzanite,
    id: colors.oldGold,
    pseudo: colors.tanzanite,
    tag: colors.ruby,
    type: colors.gemstone,
    unit: colors.gemstone,
  },
  gitGnoreAtr: {
    hash: colors.ruby,
    string: colors.gemstone,
  },
  markdown: {
    bloquotes: colors.turquoise,
    bold: colors.ruby,
    braces: colors.foreground,
    bracesBlock: colors.foreground,
    bracesParagraph: colors.turquoise,
    changed: colors.tanzanite,
    codeBlocks: colors.gemstone,
    constants: colors.tanzanite,
    deleted: colors.gemstone,
    deprecated: colors.ruby,
    error: colors.gemstone,
    filename: colors.emerald,
    horizontal: colors.diamond,
    inline: colors.diamond,
    inserted: colors.diamond,
    invalid: colors.stoneGray,
    italic: colors.emerald,
    linkText: colors.turquoise,
    links: colors.turquoise,
    list: colors.tanzanite,
  },
};
