import { colors, special } from "./colors";

export const codeColors = {
  typescript: {
    comment: colors.grey,
    importMetaNewBoolean: colors.darkerPink,
    brackets: colors.white,
    squareBrace: colors.white,
    importVar: colors.white,
    string: colors.green,
    storage: colors.red,
    constant: colors.orange,
    function: colors.yellow,
    params: colors.gold,
    class: colors.blue,
    attributes: colors.purple,
    objectMethod: colors.limon,
    this: colors.purple,
    interface: colors.cyan,
    declareVar: colors.red,
    regex: colors.purple,
    regexString: colors.darkerPink,
    test: colors.red,
  },
  react: {
    classComponent: colors.blue,
  },
  vue: {
    expression: special.vue,
    types: colors.cyan,
    test: colors.red,
  },
  json: {
    comment: colors.grey,
    brackets: colors.white,
    constant: colors.orange,
    test: colors.red,
  },
  xml: {
    meta: colors.darkerPink,
    version: colors.darkerPink,
    tag: colors.orange,
    attribute: colors.purple,
    test: colors.red,
  },
  html: {
    meta: colors.darkerPink,
    tag: colors.orange,
    vueTag: colors.green,
    attribute: colors.purple,
    text: colors.white,
    constant: colors.yellow,
    string: colors.green,
    test: colors.red,
  },
  scss: {
    keyword: colors.pink,
    meta: colors.white,
    tag: colors.orange,
    custom: colors.turquoise,
    class: colors.blue,
    id: colors.red,
    pseudo: colors.cyan,
    property: colors.purple,
    propertyValue: colors.gold,
    unit: colors.limon,
    variable: colors.darkerPink,
    variable2: colors.blue,
    comment: colors.grey,
    string: colors.green,
    bracket: colors.white,
    function: colors.yellow,
    test: colors.red,
  },
  gitGnoreAtr: {
    string: colors.orange,
    hash: colors.red,
    test: colors.red,
  },
};
